workspace:
  base: /go
  path: src/github.com/erjiaqing/PCIJudger2

pipeline:
  ProblemBuilder:
    group: build
    image: golang:1.11
    commands:
      - cd cmd/pci15/builder
      - go build
  SubmissionJudger:
    group: build
    image: golang:1.11
    commands:
      - cd cmd/pci15/judger
      - go build
  ProblemBuilder-Go1.10:
    group: build
    image: golang:1.10
    commands:
      - cd cmd/pci15/builder
      - go build
  SubmissionJudger-Go1.10:
    group: build
    image: golang:1.10
    commands:
      - cd cmd/pci15/judger
      - go build