// Code generated by protoc-gen-go. DO NOT EDIT.
// source: host.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StateMessage struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Progress             int32    `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateMessage) Reset()         { *m = StateMessage{} }
func (m *StateMessage) String() string { return proto.CompactTextString(m) }
func (*StateMessage) ProtoMessage()    {}
func (*StateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_85e40b83b4d50a8d, []int{0}
}

func (m *StateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateMessage.Unmarshal(m, b)
}
func (m *StateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateMessage.Marshal(b, m, deterministic)
}
func (m *StateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateMessage.Merge(m, src)
}
func (m *StateMessage) XXX_Size() int {
	return xxx_messageInfo_StateMessage.Size(m)
}
func (m *StateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StateMessage proto.InternalMessageInfo

func (m *StateMessage) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *StateMessage) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StateMessage) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func init() {
	proto.RegisterType((*StateMessage)(nil), "message.StateMessage")
}

func init() { proto.RegisterFile("host.proto", fileDescriptor_85e40b83b4d50a8d) }

var fileDescriptor_85e40b83b4d50a8d = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xc8, 0x2f, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55,
	0x0a, 0xe2, 0xe2, 0x09, 0x2e, 0x49, 0x2c, 0x49, 0xf5, 0x85, 0xf0, 0x85, 0x44, 0xb8, 0x58, 0x8b,
	0x41, 0x7c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x80, 0x8b, 0xb9, 0x34,
	0x33, 0x45, 0x82, 0x09, 0x2c, 0x06, 0x62, 0x0a, 0x49, 0x71, 0x71, 0x14, 0x14, 0xe5, 0xa7, 0x17,
	0xa5, 0x16, 0x17, 0x4b, 0x30, 0x2b, 0x30, 0x6a, 0xb0, 0x06, 0xc1, 0xf9, 0x49, 0x6c, 0x60, 0x3b,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x33, 0x50, 0x01, 0xb9, 0x71, 0x00, 0x00, 0x00,
}
